spring.application.name=Trace
spring.datasource.url=jdbc:postgresql://localhost:5432/codolog
spring.datasource.username=postgres
spring.datasource.password=bappi

# Hibernate ki settings hai bhai
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8082